### ISSUE TITLE
Have you made any progress in public Polys code?

### ISSUE THREAD

**Issue by omidraha** [polys-vote/polys-protocol#1]
> We plan to complete all preparations by the end of 2017.

Hi,
Is there an estimate of when will it be released publicly?
Thanks.

**Comment by kavu** [comment]
Hi, Omid!

Unfortunately, as we stated in our last README update — it takes longer than we expected:

> We’re still preparing the open-source Polys protocol code. It is taking longer than expected, but we’re doing our best to make the code public as soon as possible. We are currently auditing the Polys protocol code internally.

**Comment by omidraha** [comment]
Any update on this?
