### ISSUE TITLE
Is it still coming?

### ISSUE THREAD

**Issue by vikasr111** [polys-vote/polys-protocol#2]
Hi,

I was waiting for the source code to take a spin at it in different environments.
Is it still coming?

**Comment by kikohs** [comment]
Interested in knowing this as well. Is the project still developed? Do you plan to open-source it?

**Comment by kavu** [comment]
Let me cite the last update (see README) 

> UPD: UPD: We realize that preparation of the open-source Polys protocol code has dragged on, but we’re doing everything we possibly can to speed up the process. We’re currently resolving some legal issues and hope to publish the code in the near future.

And yes, @kikohs, Polys is still actively developed. You always can try and use our platform at polys.me

**Comment by youk** [comment]
Let me cite the README too:
> We plan to complete all preparations by the end of 2017

Are you trying to bullshit the world?
